FROM openjdk:17.0.1-jdk-slim
COPY build/libs/*.jar app.jar

ENV PROJECT_NAME=discodeit
ENV PROJECT_VERSION=1.2-M8
ENV JVM_OPT=""

EXPOSE 80
ENTRYPOINT ["sh", "-c", "java $JVM_OPT -jar app.jar --spring.application.name=$PROJECT_NAME --app.version=$PROJECT_VERSION"]